### ISSUE TITLE
오탈자 제보 

### ISSUE THREAD

**Issue by unluckyjung** [goodGid/goodGid.github.io#6]
## Where

https://github.com/goodGid/goodGid.github.io/blob/aec2d0243486c56c1b530335afa52f268fd54e48/_posts/2023-07-17-Effective-Kotlin-Sealed-Class-Dont-Need-Else-Branch.md

- 25 line

---

## How

```
* seale 키워드는 다음과 같이 정리할 수 있다.
->
* sealed 키워드는 다음과 같이 정리할 수 있다.
```

---

## Assignees
@goodGid

**Comment by goodGid** [comment]
👍
